name: Сообщение о критической ошибке
description: Сообщите об ошибке, которая заблокировала разработку вашего продукта в EDT
title: ""
labels: ["bug", "critical"]
assignees: ""
body:
  - type: markdown
    attributes:
      value: |
        Благодарим Вас, за то что оперативно сообщаете о критической ошибке!

        [Ознакомьтесь с классификацией критичности!](https://github.com/1C-Company/1c-edt-issues/blob/main/TASK_CLASSIFICATION.md)

        **Помните!** Что каждая критическая ошибка требует времени команды для рассмотрения и анализа, и это время будет взято из времени реализации уже отобранных/запланированных задач. 
  - type: textarea
    id: bug-description
    attributes:
      label: Описание ошибки
      description: Четкое и краткое описание того, в чем заключается ошибка. Явно укажите, что именно заблокировано (это не всегда бывает очевидно).
      placeholder: Расскажите нам что вы видите?
      value: "Ошибка в том что..."
    validations:
      required: true
  - type: textarea
    id: bug-reproduce
    attributes:
      label: Как воспроизвести
      description: Шаги для воспроизведения ошибки (здесь так же можно вставлять скриншоты - это очень помогает понять)
      placeholder: Что необходимо выполнить по шагам для воспроизведения ошибки?
      value: |
        1. Перейдите в `...`
        2. Кликните по `....`
        3. Прокрутите вниз до `....`
        4. Смотрите ошибку в `....`

    validations:
      required: true
  - type: textarea
    id: screenshoots
    attributes:
      label: Скриншоты
      description: |
        Если возможно, приложите скриншоты проблемы.

        Совет: не старайтесь обрезать все лишнее (по вашему мнению) на скриншоте, лучше более полный скриншот со стрелочками на проблемное место. 
      placeholder: Здесь можно вставить скриншот проблемы...
      value: ""
    validations:
      required: false
  - type: textarea
    id: expectation
    attributes:
      label: Ожидаемое поведение
      description: Четкое и краткое описание того, что вы ожидали бы в правильном поведении?
      placeholder: Какое, по вашему мнению, правильное поведение?
      value: ""
    validations:
      required: true
  - type: textarea
    id: ws-logs
    attributes:
      label: Лог рабочей области
      description: Обязательно, приложите все файлы логов из рабочей области /path/to/workspace/.metadata/*.log и файл trace.log
      placeholder: Вставьте файлы лог
      value: ""
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        [Инструкция по сбору журнала ошибок (лог ошибок)](https://its.1c.ru/db/edtdoc#content:153:hdoc:_top:лог)

        Если файл лога не получается прикрепить, это касается файла `.log`, то переименуйте его в `log.txt` и прикрепите

  - type: input
    id: edt-version
    attributes:
      label: Версия 1С:EDT
      description: "Скопируйте и вставте версию 1C:EDT из меню: Help -> About 1C:Enterprise Development Tools"
      placeholder: например, Ruby 2021.2.8.3
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Операционаня система
      description: Укажите, на каких операционных системах ошибка воспроизводится у вас?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: plug-ins
    attributes:
      label: Установленые плагины
      description: Укажите, какие плагины у вас установлены?
      multiple: true
      options:
        - Нет плагинов
        - 1C:Code style V8
        - 1C:SSL-support
        - 1C:Language Tool
        - Другие сторонние плагины `Название плагина...`

  - type: textarea
    id: additional
    attributes:
      label: Дополнительная информация
      description: |
        - Добавьте здесь любую дополнительную информацию о проблеме
        - Пример кода на котором воспроизводится ошибка, 
        - Версию типовой конфигурации 1С + объект в котором воспроизводится проблема
        - Ссылки на публичные проекты 1С в котором воспроизводится проблема
        - Версия вашей OS если это важно?
        - Версия платформы 1С [например] `8.3.18.1563`
      placeholder: Что-нибудь еще важное и полезное по этой ошибке?
      value: ""
    validations:
      required: false
